[theme]
# The accent color for widgets, borders, and active states (e.g., upload buttons)
primaryColor = "rgb(255, 255, 255)"

# The main background color of the web page
backgroundColor = "#1a391b"

# The background color for cards, sidebars, and input fields
secondaryBackgroundColor = "rgb(27, 29, 59)"

# The color of the main text on the website
textColor = "#f5f6f8"

# The global font style ("sans serif", "serif", or "monospace")
font = "sans serif"